name: Run Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
    contents: read

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            tox-env: "py310"
          - python-version: "3.11"
            tox-env: "py311"
          - python-version: "3.12"
            tox-env: "py312"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Cache Tox environments
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ matrix.tox-env }}-${{ hashFiles('**/tox.toml') }}
          restore-keys: |
            ${{ runner.os }}-tox-${{ matrix.tox-env }}-
            ${{ runner.os }}-tox-

      - name: Run Tests
        run: tox -e ${{ matrix.tox-env }}

      # Upload the coverage report as an artifact
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report-${{ matrix.python-version }}
          path: coverage_html