name: Type Check Code

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
    contents: read

jobs:
  type-check:
      name: Run Type Check Code
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"  # Use any stable Python version for type checking

        - name: Install Tox
          run: |
            python -m pip install --upgrade pip
            pip install tox

        - name: Cache Tox environments
          uses: actions/cache@v3
          with:
            path: .tox
            key: ${{ runner.os }}-tox-type-${{ hashFiles('**/tox.toml') }}
            restore-keys: |
              ${{ runner.os }}-tox-type-

        - name: Run Type Checks
          run: tox -e type